name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew ci \
          ./gradlew -p tests/kmp build \
          ./gradlew -p tests/jvm build
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
