on:
  push:
    branches: [ main ]

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    # Required for the `deploy-pages` action
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - run: |
          export JAVA_HOME=$JAVA_HOME_21_X64 # Remove when ubuntu-latest updates to Java 21
          ./gradlew librarianStaticContent
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa #v3.0.1
        with:
          path: "build/static"
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4.0.5
