name: release

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew publishAllPublicationsToCentralPortal
        env:
          OSSRH_USER: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
