name: release

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |      
          ./gradlew publishAllPublicationsToOssStagingRepository
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
