on:
  push:
    branches:
      - 'main'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    steps:
      - uses: actions/checkout@v3
      - run: |
          LIBRARIAN_VERSION_SHA1=$GITHUB_SHA ./gradlew librarianPublishToGcs
          ./gradlew librarianPublishToSnapshots
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          LIBRARIAN_GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
